#version: "3.9"
#
#services:
#  app:
#    build: ./php
#    volumes:
#      - ../src:/home/src
#  web:
#    image: nginx:1.20-alpine
#    ports:
#      - 8080:80
#    volumes:
#      - ../src:/home/src
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#    working_dir: /home/src
#  postgres:
#    image: postgres:latest
#    environment:
#      POSTGRES_USER: hoge
#      POSTGRES_PASSWORD: password
#      PGPASSWORD: password123
#      POSTGRES_DB: app
#      TZ: "Asia/Tokyo"
#    ports:
#      - 5432:5432
#    volumes:
#      - postgres:/var/lib/postgresql/data
#
#volumes:
#  postgres:


version: '3'

services:
  php:
    build: ./docker/php
    volumes:
      - ./src:/var/www

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

#  db:
#    image: mysql:5.7
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: app
#      MYSQL_USER: hoge
#      MYSQL_PASSWORD: password
#      TZ: 'Asia/Tokyo'
#    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#    volumes:
#      - ./docker/db/data:/var/lib/mysql
#      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
#      - ./docker/db/sql:/docker-entrypoint-initdb.d
#    ports:
#      - 3306:3306
  db:
    image: postgres:14-bullseye
    environment:
      POSTGRES_USER: hoge
      POSTGRES_PASSWORD: password
      PGPASSWORD: password123
      POSTGRES_DB: app
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data

  node:
    image: node:14.18-buster
    tty: true
    volumes:
      - ./src:/var/www
    working_dir: /var/www
