version: "3.9"

services:
  app:
    build: ./php
    volumes:
      - ../src:/home/src
  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ../src:/home/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /home/src
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: hoge
      POSTGRES_PASSWORD: password
      PGPASSWORD: password123
      POSTGRES_DB: app
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
